name: Setup Python env
description: Install Python requirements and testing tools

inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.10'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '${{ inputs.python-version }}'
    - name: Update pip
      run: python -m pip install --upgrade pip
      shell: bash
    - name: Install dependencies and tools
      run: |
        pip install flake8 pytest coverage
        pip install -r requirements.txt
      shell: bash
    - name: Generate UI files
      run: python ./build_tools/convert_ui_files.py
      shell: bash
    - name: Install drivers required for Qt/PySide
      run: apt-get install -y  libgl1-mesa-dev libglib2.0-0
      shell: bash
