version: "2"

checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 15
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 15
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
  return-statements:
    config:
      threshold: 6

exclude_patterns:
  - "**/*_test.py"
