from lookup.wiktionary.internal_logic.card_matching import match_definition_sets
from lookup.wiktionary.internal_logic.localized_lookup import lookup_definition_sets
from lookup.wiktionary.internal_logic.web_api import search_articles, retrieve_articles
