from lookup.wiktionary.language_support.english import EnglishLocaleParser
from lookup.wiktionary.language_support.german import GermanLocaleParser
from lookup.wiktionary.language_support.abstract import WiktionaryLocaleParser, WiktionaryArticle
