name: Setup Qt dependencies
description: Install required graphic drivers and generate UI files

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Install drivers required for Qt/PySide
      run: sudo apt-get install -y  libgl1-mesa-dev libglib2.0-0
      shell: bash
    - name: Generate UI files
      run: python ./build_tools/convert_ui_files.py
      shell: bash
