name: Measure coverage

on:
  push:
  schedule:
    - cron: '0 9 * * 1,4'

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      matrix:
        python-version: [ '3.10' ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/actions/setup_python
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Setup QT drivers and generate UI files
        uses: ./.github/actions/setup_qt
      - name: Test and gather coverage data
        run: coverage run --source=core,lookup,ui -m unittest discover -p *_test.py
      - name: Upload coverage data
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
