name: Test and build

on:
  push:
  schedule:
    - cron: '0 9 * * 1,4'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    strategy:
      matrix:
        python-version: [ '3.10' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: ./.github/actions/setup_python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint
        run: flake8 . --config=.github/.flake8 --exit-zero

  test:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: ./.github/actions/setup_python
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Setup QT drivers and generate UI files
        uses: ./.github/actions/setup_qt
      - name: Test and gather coverage data
        run: |
          coverage run -m unittest discover -p *_test.py
          coverage xml -i
      - name: Upload coverage data
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
