name: Flake8 Lint

on:
  push:
  schedule:
    - cron: '0 9 * * 1,4'

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    strategy:
      matrix:
        python-version: [ '3.10' ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/actions/setup_python
        with:
          python-version: ${{ matrix.python-version }}
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "121"
          per-file-ignores: "__init__.py:F401"